controller_list:
  - name: fake_l_manipulator_controller
    joints:
      - l_shoulder_pan_joint
      - l_shoulder_lift_joint
      - l_elbow_joint
      - l_wrist_1_joint
      - l_wrist_2_joint
      - l_wrist_3_joint
  - name: fake_r_manipulator_controller
    joints:
      - r_shoulder_pan_joint
      - r_shoulder_lift_joint
      - r_elbow_joint
      - r_wrist_1_joint
      - r_wrist_2_joint
      - r_wrist_3_joint
  - name: fake_l_endeffector_controller
    joints:
      []
  - name: fake_r_endeffector_controller
    joints:
      []
  - name: fake_dual_manipulator_controller
    joints:
      - l_shoulder_pan_joint
      - l_shoulder_lift_joint
      - l_elbow_joint
      - l_wrist_1_joint
      - l_wrist_2_joint
      - l_wrist_3_joint
      - r_shoulder_pan_joint
      - r_shoulder_lift_joint
      - r_elbow_joint
      - r_wrist_1_joint
      - r_wrist_2_joint
      - r_wrist_3_joint